#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Reg
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Reg/Login.cshtml")]
    public partial class Login : System.Web.Mvc.WebViewPage<Cotide.Web.Controllers.ViewModels.User.UserLoginViewModel>
    {
        public Login()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Reg\Login.cshtml"
  
    ViewBag.Title = "用户登录";
    Layout = "~/Views/Shared/_MainLayout.cshtml"; 


            
            #line default
            #line hidden


DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\Reg\Login.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\Reg\Login.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral(@"
    <style type=""text/css"">
       
        .form-signin
        {
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }
    </style>
");


});

WriteLiteral(@"
<div class=""row-fluid"" style=""padding-top: 15px;"">
    <ul class=""nav nav-tabs"">
        <li class=""active""><a href=""javascript:void(0);"">用户登录</a> </li> 
    </ul>
</div>
<div class=""row-fluid"">
    <!-- 登录 -->
    <div id=""loginForm"" class=""row"" style=""margin-left:0px;width:550px;margin:0 auto;"">
");


            
            #line 34 "..\..\Views\Reg\Login.cshtml"
         using (Html.BeginForm(Html.BeginForm
                            ("Login",
                            "Reg",
                            FormMethod.Post,
                            new
                                {
                                    @Id = "login-form",
                                    @class = "form-signin"
                                })))
        {
      

            
            #line default
            #line hidden
WriteLiteral("            <p>\r\n                ");


            
            #line 46 "..\..\Views\Reg\Login.cshtml"
           Write(Html.ValidationExSummary("login-form"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n");



WriteLiteral("            <p>\r\n                <table>\r\n                    <tr>\r\n             " +
"           <td style=\"width: 80px;\">\r\n                            ");


            
            #line 52 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.LabelFor(x => x.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          ");


            
            #line 55 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.TextBoxExFor(x => x.UserName, new
               {
                   @style = "width: 180px; color: Silver;",
                   @title = "手机号/账号/邮箱",
                   @maxlength = "50",
                   @placeholder = "管理员帐号"
               }, new ValidateOption()
               {
                   EmptyMsg = "您还没输入用户账户",
                   Description =
                       "手机号/账号/邮箱",
                   FocusMsg = "账户格式：3-50位字符",
                   Min = 3,
                   Max = 50,
                   RangeMsg = "请确保账户在3-50位字符内"
               }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 71 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.ValidationMessageExFor(x => x.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                    </tr>\r\n                    <" +
"tr>\r\n                        <td>\r\n                            ");


            
            #line 76 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.LabelFor(x => x.Paw));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n                  " +
"          ");


            
            #line 79 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.PasswordExFor(x => x.Paw, new
               {
                   @style = "width: 180px;",
                   @title = "密码",
                   @maxlength = "100",
                   @placeholder = "密码"
               }, new PassValidateOption()
               {
                   EmptyMsg = "请输入密码",
                   Min = 5,
                   Max
                       = 20,
                   RangeMsg = "密码格式：5-20位字符"
               }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            ");


            
            #line 93 "..\..\Views\Reg\Login.cshtml"
                       Write(Html.ValidationMessageExFor(x => x.Paw));

            
            #line default
            #line hidden
WriteLiteral(@"
                        </td>
                    </tr>
                            <tr style=""width: 300px;"">
                        <td>
                           记住密码
                        </td>
                        <td>
                           ");


            
            #line 101 "..\..\Views\Reg\Login.cshtml"
                      Write(Html.CheckBox("savePaw"));

            
            #line default
            #line hidden
WriteLiteral(@"
                        </td>
                    </tr>
                    <tr>
                        <td>
                        </td>
                        <td>
                            <div class=""blank_20"">
                            </div>
                            <button class=""btn  btn-primary"" type=""submit"">
                                <i class=""icon-user""></i>&nbsp; 登录
                            </button>
                            <button class=""btn"" onclick=""RestForm()"" type=""button"">
                                重置
                            </button>
                        </td>
                    </tr>
                </table>
            </p>
");


            
            #line 120 "..\..\Views\Reg\Login.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <script type=\"text/javascript\">\r\n        function RestForm() {\r\n " +
"           $(\"#UserName\").val(\"\");\r\n            $(\"#Paw\").val(\"\");\r\n        }\r\n " +
"   </script>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
