#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_BaseLayout.cshtml")]
    public partial class BaseLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public BaseLayout()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\_BaseLayout.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
"/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xh" +
"tml\">\r\n<head>\r\n    <title>");


            
            #line 7 "..\..\Views\Shared\_BaseLayout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title><meta name=\"keywords\" content=\"");


            
            #line 7 "..\..\Views\Shared\_BaseLayout.cshtml"
                                                           Write(ViewBag.Keywords);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <meta name=\"description\" content=\"");


            
            #line 8 "..\..\Views\Shared\_BaseLayout.cshtml"
                                 Write(ViewBag.Description);

            
            #line default
            #line hidden
WriteLiteral("\" />\r ");


            
            #line 9 "..\..\Views\Shared\_BaseLayout.cshtml"
Write(Html.StyleSheet("bootstrap/bootstrap.min.css"));

            
            #line default
            #line hidden
WriteLiteral("  ");


            
            #line 9 "..\..\Views\Shared\_BaseLayout.cshtml"
                                             Write(Html.StyleSheet("bootstrap/bootstrap-responsive.min.css"));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 9 "..\..\Views\Shared\_BaseLayout.cshtml"
                                                                                                        Write(Html.JqueryScript());

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 9 "..\..\Views\Shared\_BaseLayout.cshtml"
                                                                                                                             Write(Html.JavaScript("cotide/cotide.core.js"));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 9 "..\..\Views\Shared\_BaseLayout.cshtml"
                                                                                                                                                                       Write(Html.JavaScript("cotide/cotide.dialog.init.js"));

            
            #line default
            #line hidden
WriteLiteral("  \r\n    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->\r\n    <!--[if lt " +
"IE 9]> \r\n    ");


            
            #line 12 "..\..\Views\Shared\_BaseLayout.cshtml"
Write(Html.JavaScript("lib/html5.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <![endif]-->   ");


            
            #line 13 "..\..\Views\Shared\_BaseLayout.cshtml"
              Write(RenderSection("Head",false));

            
            #line default
            #line hidden
WriteLiteral(" \r\n</head>\r\n<body>  ");


            
            #line 15 "..\..\Views\Shared\_BaseLayout.cshtml"
   Write(RenderSection("Content", false));

            
            #line default
            #line hidden
WriteLiteral("  </body> </Html>\r\n");


        }
    }
}
#pragma warning restore 1591
