#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
    using Cotide.Domain.Contracts.Task;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_BlogManagerLayout.cshtml")]
    public partial class BlogManagerLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public BlogManagerLayout()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
  
     Layout = "~/Views/Shared/_BaseLayout.cshtml";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 6 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
Write(Html.StyleSheet("bootstrap/docs.css"));

            
            #line default
            #line hidden
WriteLiteral(@"
    <style type=""text/css"">
        body
        {
            position: relative;
            margin: 10px;
        }
        a
        {
            color: #a3163c;
            text-decoration: none;
        }
        .content_left
        {
            float: left;
            padding-right: 8px;
            padding-left: 5px;
            width: 20%;
        }
        .content_right
        {
            float: left;
            width: 75%;
        }
        .backToTop
        {
            display: none;
            width: 18px;
            line-height: 1.2;
            padding: 5px 0;
            background-color: #C00;
            color: #fff;
            font-size: 12px;
            text-align: center;
            position: fixed;
            _position: absolute;
            right: 10px;
            bottom: 100px;
            _bottom: auto;
            cursor: pointer;
            opacity: .6;
            filter: Alpha(opacity=60);
        }
    </style>
    ");


            
            #line 50 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
Write(Html.JavaScript("bootstrap/bootstrap-dropdown.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n     ");


            
            #line 51 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
Write(Html.StyleSheet("pagerStyle.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 52 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("Content", () => {

WriteLiteral("\r\n    <!-- 滚动条/开始 -->\r\n    <div class=\"navbar navbar-inverse\">\r\n");


            
            #line 57 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
          Html.RenderAction("UserNav", "Blog");

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n    <!-- 滚动条/结束 -->\r\n    <div class=\"container-fluid\">\r\n        <div " +
"class=\"row\">\r\n            <div class=\"content_right bs-docs-sidebar\" style=\"padd" +
"ing: 0px 20px 0px 10px;\">\r\n\r\n                 ");


            
            #line 64 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
            Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"content_left\">\r\n");


            
            #line 67 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
                 Html.RenderAction("UserMenu", "BlogManager");

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div> \r\n    </div>\r\n");


            
            #line 71 "..\..\Views\Shared\_BlogManagerLayout.cshtml"
         Html.RenderPartial("~/Views/Shared/_MainBottom.cshtml");

            
            #line default
            #line hidden

});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
