#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_MainBottom.cshtml")]
    public partial class MainBottom : System.Web.Mvc.WebViewPage<dynamic>
    {
        public MainBottom()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\_MainBottom.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral(@"  <footer class=""footer"">   <div class=""container"">  <p> © 2013. Powered by <a href=""http://www.cotide.com"" target=""_blank""> 李小潮</a>
 <script type=""text/javascript"" src=""http://v3.jiathis.com/code/jia.js?uid=1349579626298337"" charset=""utf-8""></script><script src=""http://s25.cnzz.com/stat.php?id=4368997&web_id=4368997&show=pic"" language=""JavaScript""></script><script type=""text/javascript""> $(function () { var $backToTopTxt = ""返回顶部"", $backToTopEle = $('<div class=""backToTop""></div>').appendTo($(""body"")).text($backToTopTxt).attr(""title"", $backToTopTxt).click(function () { $(""html, body"").animate({ scrollTop: 0 }, 120) }), $backToTopFun = function () { var st = $(document).scrollTop(), winh = $(window).height(); (st > 0) ? $backToTopEle.show() : $backToTopEle.hide(); if (!window.XMLHttpRequest) { $backToTopEle.css(""top"", st + winh - 166) } }; $(window).bind(""scroll"", $backToTopFun); $(function () { $backToTopFun() }) })</script>  </p>   </div> </footer>
");


        }
    }
}
#pragma warning restore 1591
