#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\_MainLayout.cshtml"
    using Cotide.Domain.Contracts.Task;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_MainLayout.cshtml")]
    public partial class MainLayout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public MainLayout()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Shared\_MainLayout.cshtml"
  
    ViewBag.Title = "首页";
    Layout = "~/Views/Shared/_BaseLayout.cshtml";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral(@"
    <style type=""text/css"">
        body
        {
            position: relative;
            margin: 10px;
        }
        a
        {
            color: #088738;
            text-decoration: none;
        
        }
        
        .container
        {
            width: 940px;
        }
    </style>
    ");


            
            #line 25 "..\..\Views\Shared\_MainLayout.cshtml"
Write(Html.JavaScript("bootstrap/bootstrap-dropdown.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 26 "..\..\Views\Shared\_MainLayout.cshtml"
Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


DefineSection("Content", () => {

WriteLiteral(" \r\n    <div class=\"container\">\r\n        \r\n        <div>\r\n            ");


            
            #line 32 "..\..\Views\Shared\_MainLayout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
        </div>
        <!-- 底部 -->
        <!-- 滚动条/结束 --> 
        <!-- 底部 -->
        <div class=""row-fluid"">
          <hr />
       <footer class=""footer"">   <div class=""container"">  <p> © 2013. Powered by <a href=""http://www.cotide.com"" target=""_blank""> 李小潮</a>
    </p> </div> </footer>
    </div>
    </div>
     
");


});

WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
