#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\BlogManager\_UserMenu.cshtml"
    using Cotide.Domain.Enum;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\BlogManager\_UserMenu.cshtml"
    using Cotide.Web.Controllers.ViewModels;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/_UserMenu.cshtml")]
    public partial class UserMenu : System.Web.Mvc.WebViewPage<UserViewModel>
    {
        public UserMenu()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\_UserMenu.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden



WriteLiteral("<legend>\r\n    <lable>  账号</lable>\r\n</legend>\r\n<ul class=\"nav nav-pills nav-stacke" +
"d\">\r\n    <li>\r\n        ");


            
            #line 12 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("个人信息", "MyAccount", "BlogManager", null, new { @title = "个人信息"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n</ul>\r\n<legend>\r\n    <lable>  文章类型管理</lable>\r\n</legend>\r\n<ul class=\"" +
"nav nav-pills nav-stacked\">\r\n    <li>\r\n        ");


            
            #line 20 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("文章分类", "ArticleType", "BlogManager", null, new { @title = "文章分类"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n    <li>\r\n        ");


            
            #line 23 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("文章标签", "ArticleTag", "BlogManager", null, new { @title = "文章标签"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n</ul>\r\n\r\n<legend>\r\n    <lable>  文章管理</lable>\r\n</legend>\r\n<ul class=\"" +
"nav nav-pills nav-stacked\">\r\n    <li>\r\n        ");


            
            #line 32 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("发布文章", "Index", "BlogManager", null, new { @title = "发布文章"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n    <li>\r\n        ");


            
            #line 35 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("文章管理", "ArticleManger", "BlogManager", null, new { @title = "文章管理"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n</ul> \r\n\r\n<legend>\r\n    <lable> 作品管理</lable>\r\n</legend>\r\n<ul class=\"" +
"nav nav-pills nav-stacked\">\r\n    <li>\r\n        ");


            
            #line 44 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("作品类型管理", "ProjectType", "BlogManager", null, new { @title = "作品类型管理" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li> \r\n        <li>\r\n        ");


            
            #line 47 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("新增作品", "AddProject", "BlogManager", null, new { @title = "新增作品" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li> \r\n     <li>\r\n        ");


            
            #line 50 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("作品管理", "Project", "BlogManager", null, new { @title = "作品管理" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li> \r\n</ul> \r\n<legend>\r\n    <lable>  链接管理</lable>\r\n</legend>\r\n<ul class=\"" +
"nav nav-pills nav-stacked\">\r\n    <li>\r\n        ");


            
            #line 58 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("链接管理", "Link", "BlogManager", null, new { @title = "链接管理" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li> \r\n</ul> \r\n");


            
            #line 61 "..\..\Views\BlogManager\_UserMenu.cshtml"
 if (Model.UserRole.HasFlag(UserLoginRole.Admin))
{ 

            
            #line default
            #line hidden
WriteLiteral(" <legend>\r\n    <lable> <i class=\"icon-wrench\"></i> 广告管理</lable>\r\n</legend>\r\n");



WriteLiteral("    <ul class=\"nav nav-pills nav-stacked\">\r\n <li>\r\n        ");


            
            #line 68 "..\..\Views\BlogManager\_UserMenu.cshtml"
   Write(Html.ActionLink("首页广告", "AdManager", "BlogManager", null, new { @title = "首页广告" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </li>\r\n    </ul>\r\n");


            
            #line 71 "..\..\Views\BlogManager\_UserMenu.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
