#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\BlogManager\AddProject.cshtml"
    using Cotide.Web.Controllers.BlogManager.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/AddProject.cshtml")]
    public partial class AddProject : System.Web.Mvc.WebViewPage<AddProjectModel>
    {
        public AddProject()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\AddProject.cshtml"
  
    ViewBag.Title = "AddProject";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden



DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\BlogManager\AddProject.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 9 "..\..\Views\BlogManager\AddProject.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 10 "..\..\Views\BlogManager\AddProject.cshtml"
Write(Html.JavaScript("kindeditor/kindeditor-min.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 11 "..\..\Views\BlogManager\AddProject.cshtml"
Write(Html.JavaScript("kindeditor/lang/zh_CN.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<script type=\"text/javascript\">\r\n    var editor;\r\n    $(function () {\r\n        " +
"KindEditor.ready(function (K) {\r\n            editor = K.create(\'#Content\', {\r\n  " +
"              themeType: \'default\',\r\n                uploadJson: \'");


            
            #line 19 "..\..\Views\BlogManager\AddProject.cshtml"
                        Write(Url.Action("UploadFile", "FileMamager"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                fileManagerJson: \'");


            
            #line 20 "..\..\Views\BlogManager\AddProject.cshtml"
                             Write(Url.Action("MyFile", "FileMamager"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                allowFileManager: true,
                items: ['source', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
                        'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
                        'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
                        'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
                        'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                        'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 'multiimage',
                        'flash', 'media', 'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
                        'anchor', 'link', 'unlink', ]
            });
        });
    });


    function Check() {
        if ($.trim($(""#ProjectName"").val()) == """") {
            alert('请输入作品标题！');
            return false;
        }
        if (editor.isEmpty()) {
            alert('请输入作品内容！');
            return false;
        }
        if ($(""#Introduction"").val() == """") {
            alert('请输入作品简介!');
            return false;
        }
        if ($(""#ProjectTypeId"").val() <= 0) {
            alert('请输入作品所属分类!');
            return false;
        }
    }
</script>
<legend>
    <h4>
        发布作品</h4>
</legend>
");


            
            #line 58 "..\..\Views\BlogManager\AddProject.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 59 "..\..\Views\BlogManager\AddProject.cshtml"
    using (Html.BeginForm("AddProject", "BlogManager",FormMethod.Post,
       new { @id = "AddProjectFrom", @onSubmit = "return Check()", @enctype = "multipart/form-data" }))
       { 

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            作品标题 ：</label>\r\n       ");


            
            #line 65 "..\..\Views\BlogManager\AddProject.cshtml"
  Write(Html.TextBoxFor(x => x.ProjectName, new {@style = "width: 650px;", @class = "half"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        ");


            
            #line 68 "..\..\Views\BlogManager\AddProject.cshtml"
   Write(Html.TextAreaFor(x => x.Content, new {@style = "width: 100%;height: 400px;", @class = "half"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            作品简介 ：</label>\r\n        ");


            
            #line 73 "..\..\Views\BlogManager\AddProject.cshtml"
   Write(Html.TextAreaFor(x => x.Introduction,new {@style = "width: 90%;height: 130px;", @class = "half"}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            分类 ：\r\n        </label>\r\n  " +
"      ");


            
            #line 79 "..\..\Views\BlogManager\AddProject.cshtml"
   Write(Html.DropDownListFor(x => x.ProjectTypeId, ViewData["ProjectTypes"] as List<SelectListItem>));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            作品图片 ：\r\n        </label>\r\n" +
"        <input type=\"file\" name=\"file\" />\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            网址 ：\r\n        </label>\r\n  " +
"      ");


            
            #line 91 "..\..\Views\BlogManager\AddProject.cshtml"
   Write(Html.TextBoxFor(x => x.WebSite, new {@style = "width: 650px;", @class = "half"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <button type=\"submit\" class=\"btn btn-primary\">\r\n            保存\r\n" +
"        </button>\r\n    </p>\r\n");


            
            #line 98 "..\..\Views\BlogManager\AddProject.cshtml"
    }
            
            #line default
            #line hidden
WriteLiteral("  ");


        }
    }
}
#pragma warning restore 1591
