#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/ArticleTag.cshtml")]
    public partial class ArticleTag : System.Web.Mvc.WebViewPage<Cotide.Framework.Collections.PagedList<Cotide.Domain.Dtos.ArticleTagDto>>
    {
        public ArticleTag()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\ArticleTag.cshtml"
  
    ViewBag.Title = "ArticleTag";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden


DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    ");


            
            #line 9 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.StyleSheet("lib/jquery-ui-1.8.11.custom.css"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 10 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.JavaScript("lib/jquery-ui.min.js"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 11 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.JavaScript("cotide/cotide.dialog.init.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n");


});

WriteLiteral(@"
<script type=""text/javascript"">

    function DeleteArticleTag(obj) {
        if (confirm('是否删除该文章标签')) {
            location = $(obj).attr(""ref"");
        }
    }

    function UpdateArticleType(obj) {
        var url = $(obj).attr(""ref"");
        cotide.dialog.open(url, ""修改文章标签"", 480, 230, function () {
            location = '");


            
            #line 24 "..\..\Views\BlogManager\ArticleTag.cshtml"
                   Write(Url.Action("ArticleTag", "BlogManager"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        });\r\n    } \r\n</script>\r\n<legend>\r\n    <h4>\r\n        文章标签管理</h4>\r\n</le" +
"gend>\r\n  ");


            
            #line 32 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 33 "..\..\Views\BlogManager\ArticleTag.cshtml"
 using (Html.BeginForm("ArticleTag", "BlogManager", FormMethod.Post, new { id = "AddArticleTagFrom" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <h5>\r\n        新增文章标签</h5>\r\n");



WriteLiteral("               <p>\r\n        ");


            
            #line 38 "..\..\Views\BlogManager\ArticleTag.cshtml"
   Write(Html.ValidationExSummary("AddArticleTagFrom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            文章标签名称 ：</label> \r\n       " +
"   ");


            
            #line 43 "..\..\Views\BlogManager\ArticleTag.cshtml"
     Write(Html.TextBoxEx("articleTagName", new
     {
         @style = "width: 500px; color: Silver;",
         @title = "文章标签名称",
         @maxlength = "30",
         @placeholder = "请输入文章标签名称(必填)"
     }, new ValidateOption()
     {
         EmptyMsg = "您还没输入文章标签名称",
         Description =
             "文章标签名称格式:1-30位字符",
         Min = 1,
         Max = 255,
         RangeMsg = "请确保文章标签名称在1-30位字符内"
     }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 58 "..\..\Views\BlogManager\ArticleTag.cshtml"
   Write(Html.ValidationMessageEx("articleTagName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </p> \r\n");



WriteLiteral("    <p>\r\n       <button type=\"submit\" class=\"btn btn-primary\">\r\n            保存\r\n " +
"       </button>\r\n    </p>\r\n");


            
            #line 66 "..\..\Views\BlogManager\ArticleTag.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral(@"<h5>
    您已拥有的文章标签</h5>
<!-- 文章类别列表/开始 -->
<table  class=""table  table-hover"">
    <tr class=""info"">
        <td>
            序号
        </td>
        <td>
            文章标签名称
        </td> 
        <td>
            状态
        </td>
        <td>
            修改
        </td>
        <td>
            彻底删除
        </td>
    </tr>
");


            
            #line 88 "..\..\Views\BlogManager\ArticleTag.cshtml"
     for (int i = 0; i < Model.Count; i++)
    { 

            
            #line default
            #line hidden

            
            #line 90 "..\..\Views\BlogManager\ArticleTag.cshtml"
WriteLiteral("        <tr ");

            
            #line default
            #line hidden
            
            #line 90 "..\..\Views\BlogManager\ArticleTag.cshtml"
             if ((i % 2) == 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("class=\"\'firseTd\'\"\r\n");


            
            #line 93 "..\..\Views\BlogManager\ArticleTag.cshtml"
                 }
            
            #line default
            #line hidden
WriteLiteral("  >\r\n            <td>\r\n                ");


            
            #line 95 "..\..\Views\BlogManager\ArticleTag.cshtml"
            Write(i + 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 98 "..\..\Views\BlogManager\ArticleTag.cshtml"
           Write(Model[i].TagName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td> \r\n            <td>\r\n                ");


            
            #line 101 "..\..\Views\BlogManager\ArticleTag.cshtml"
           Write(Html.ActionLink(Model[i].IsShow ? "显示" : "隐藏", "SetArticleTagIsShow", new { @articleTagId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                <a    ref=\"");


            
            #line 104 "..\..\Views\BlogManager\ArticleTag.cshtml"
                      Write(Url.Action("UpdateArticleTag", "BlogManager", new { @articleTagId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0);\"\r\n                          onclick=\"UpdateArticleTyp" +
"e(this)\"  >\r\n                    修改</a>\r\n            </td>\r\n            <td>\r\n  " +
"              <a href=\'javascript:void(0);\'   ref=\"");


            
            #line 109 "..\..\Views\BlogManager\ArticleTag.cshtml"
                                                Write(Url.Action("DeleteArticleTag"));

            
            #line default
            #line hidden
WriteLiteral("?articleTagId=");


            
            #line 109 "..\..\Views\BlogManager\ArticleTag.cshtml"
                                                                                             Write(Model[i].Id);

            
            #line default
            #line hidden
WriteLiteral(" \"  \r\n                  onclick=\"DeleteArticleTag(this)\">   删除</a>\r\n            <" +
"/td>\r\n        </tr>\r\n");


            
            #line 113 "..\..\Views\BlogManager\ArticleTag.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 114 "..\..\Views\BlogManager\ArticleTag.cshtml"
     if (Model.Count <= 0)
    {  

            
            #line default
            #line hidden
WriteLiteral("        <tr class=\"firseTd\">\r\n            <td colspan=\"6\" style=\"text-align: cent" +
"er;\">\r\n                暂无数据\r\n            </td>\r\n        </tr>\r\n");


            
            #line 121 "..\..\Views\BlogManager\ArticleTag.cshtml"
                       
    }

            
            #line default
            #line hidden
WriteLiteral("    <tfoot>\r\n        <tr>\r\n            <td colspan=\"6\">\r\n                共有 ");


            
            #line 126 "..\..\Views\BlogManager\ArticleTag.cshtml"
              Write(Model.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条记录\r\n            </td>\r\n        </tr>\r\n    </tfoot>\r\n</table>\r\n<!-- 分页/开始 --> \r\n" +
"    ");


            
            #line 132 "..\..\Views\BlogManager\ArticleTag.cshtml"
Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
WriteLiteral(" \r\n");


        }
    }
}
#pragma warning restore 1591
