#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/ArticleType.cshtml")]
    public partial class ArticleType : System.Web.Mvc.WebViewPage<Cotide.Framework.Collections.PagedList<Cotide.Domain.Dtos.ArticleTypeDto>>
    {
        public ArticleType()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\ArticleType.cshtml"
  
    ViewBag.Title = "ArticleType";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 6 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    ");


            
            #line 8 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(Html.StyleSheet("lib/jquery-ui-1.8.11.custom.css"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 9 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(Html.JavaScript("lib/jquery-ui.min.js"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 10 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(Html.JavaScript("cotide/cotide.dialog.init.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n");


});

WriteLiteral("\r\n");


WriteLiteral(@"      <script type=""text/javascript""> 
          function DeleteArticleType(obj) {
              if (confirm('是否删除该文章分类')) {
                  location = $(obj).attr(""ref"");
              }
          }
          function UpdateArticleType(obj) { 
              var url = $(obj).attr(""ref"");
              cotide.dialog.open(url, ""修改文章分类"", 480, 230, function () { 
                  location = '");


            
            #line 22 "..\..\Views\BlogManager\ArticleType.cshtml"
                         Write(Url.Action("ArticleType", "BlogManager"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n              });\r\n          } \r\n  </script> \r\n<legend>\r\n        <h4>\r\n      " +
"       文章类别管理</h4>\r\n    </legend>\r\n    ");


            
            #line 30 "..\..\Views\BlogManager\ArticleType.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 31 "..\..\Views\BlogManager\ArticleType.cshtml"
      using (Html.BeginForm("ArticleType", "BlogManager", FormMethod.Post, new { id = "AddArticleTypeFrom" }))
     { 


            
            #line default
            #line hidden
WriteLiteral("        <h5>\r\n        新增文章分类</h5>\r\n");



WriteLiteral("          <p>\r\n        ");


            
            #line 37 "..\..\Views\BlogManager\ArticleType.cshtml"
   Write(Html.ValidationExSummary("AddArticleTypeFrom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            文章类别名称 ：</label>\r\n\r\n      " +
"    ");


            
            #line 43 "..\..\Views\BlogManager\ArticleType.cshtml"
     Write(Html.TextBoxEx("articleTypeName", new
     {
         @style = "width: 500px; color: Silver;",
         @title = "文章类别名称",
         @maxlength = "30",
         @placeholder = "请输入文章类别名称(必填)"
     }, new ValidateOption()
     {
         EmptyMsg = "您还没输入文章类别",
         Description =
             "文章类别格式:1-30位字符",
         Min = 1,
         Max = 255,
         RangeMsg = "请确保文章类别在1-30位字符内"
     }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 58 "..\..\Views\BlogManager\ArticleType.cshtml"
   Write(Html.ValidationMessageEx("articleTypeName"));

            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n          \r\n    </p>\r\n");



WriteLiteral("    <p>\r\n      <button type=\"submit\" class=\"btn btn-primary\"> 保存 </button>\r\n    <" +
"/p>\r\n");


            
            #line 65 "..\..\Views\BlogManager\ArticleType.cshtml"
     } 

            
            #line default
            #line hidden
WriteLiteral(@"    <h5>
        您已拥有的文章分类</h5> 
<table  class=""table  table-hover"">
                <tr class=""info"">
            <td>
                序号
            </td>
            <td>
                文章分类名称
            </td> 
            <td>
                状态
            </td>
            <td>
                修改
            </td>
            <td>
                彻底删除
            </td>
        </tr>
");


            
            #line 86 "..\..\Views\BlogManager\ArticleType.cshtml"
          for (int i = 0; i < Model.Count; i++)
         {

            
            #line default
            #line hidden

            
            #line 88 "..\..\Views\BlogManager\ArticleType.cshtml"
WriteLiteral("             <tr ");

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\BlogManager\ArticleType.cshtml"
                  if ((i % 2) == 0)
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("class=\"\'firseTd\'\"\r\n");


            
            #line 91 "..\..\Views\BlogManager\ArticleType.cshtml"
                 }
            
            #line default
            #line hidden
WriteLiteral("  >\r\n                 <td>\r\n                     ");


            
            #line 93 "..\..\Views\BlogManager\ArticleType.cshtml"
                 Write(i + 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n                 </td>\r\n                 <td>\r\n                     ");


            
            #line 96 "..\..\Views\BlogManager\ArticleType.cshtml"
                Write(Model[i].TypeName);

            
            #line default
            #line hidden
WriteLiteral(" \r\n                 </td>\r\n                  \r\n                 <td>\r\n           " +
"          ");


            
            #line 100 "..\..\Views\BlogManager\ArticleType.cshtml"
                Write(Html.ActionLink(Model[i].IsShow ? "显示" : "隐藏", "SetArticleTypeIsShow", new { @articleTypeId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("  \r\n                 </td>\r\n                 <td>\r\n                     <a ref=\"");


            
            #line 103 "..\..\Views\BlogManager\ArticleType.cshtml"
                        Write(Url.Action("UpdateArticleType", "BlogManager", new { @articleTypeId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0);\"\r\n                          onclick=\"UpdateArticleTyp" +
"e(this)\">修改</a>\r\n                 </td>\r\n                 <td>\r\n                " +
"     <a href=\'javascript:void(0);\'  ref=\"");


            
            #line 107 "..\..\Views\BlogManager\ArticleType.cshtml"
                                                    Write(Url.Action("DeleteArticleType"));

            
            #line default
            #line hidden
WriteLiteral("?articleTypeId=");


            
            #line 107 "..\..\Views\BlogManager\ArticleType.cshtml"
                                                                                                   Write(Model[i].Id);

            
            #line default
            #line hidden
WriteLiteral(" \" \r\n                        onclick=\"DeleteArticleType(this)\">删除</a>\r\n          " +
"       </td>\r\n             </tr>\r\n");


            
            #line 111 "..\..\Views\BlogManager\ArticleType.cshtml"
         }

            
            #line default
            #line hidden

            
            #line 112 "..\..\Views\BlogManager\ArticleType.cshtml"
         if (Model.Count <= 0)
        {  

            
            #line default
            #line hidden
WriteLiteral("        <tr class=\"firseTd\">\r\n            <td colspan=\"6\" style=\"text-align: cent" +
"er;\">\r\n                暂无数据\r\n            </td>\r\n        </tr>\r\n");


            
            #line 119 "..\..\Views\BlogManager\ArticleType.cshtml"
        } 

            
            #line default
            #line hidden
WriteLiteral("        <tfoot>\r\n            <tr>\r\n                <td colspan=\"6\">\r\n            " +
"        共有 ");


            
            #line 123 "..\..\Views\BlogManager\ArticleType.cshtml"
                  Write(Model.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条记录\r\n                </td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n " +
"   <!-- 分页/开始 --> \r\n        ");


            
            #line 129 "..\..\Views\BlogManager\ArticleType.cshtml"
   Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
WriteLiteral(" ");


        }
    }
}
#pragma warning restore 1591
