#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/ArticleManger.cshtml")]
    public partial class ArticleManger : System.Web.Mvc.WebViewPage<Cotide.Framework.Collections.PagedList<Cotide.Domain.Dtos.ArticleDto> >
    {
        public ArticleManger()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\ArticleManger.cshtml"
  
    ViewBag.Title = "ArticleManger";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";
 

            
            #line default
            #line hidden

WriteLiteral(@"    
         <script type=""text/javascript"">
             function DeleteArticle(obj) {
                 if (confirm('是否删除该文章')) {
                     location = $(obj).attr(""ref"");
                 }
             } 
  </script> 
                <legend>
    <h4>
        您所拥有的文章</h4>
</legend>
");


            
            #line 18 "..\..\Views\BlogManager\ArticleManger.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral(@"
            <!-- 文章类别列表/开始 -->
            <table  class=""table  table-hover"">
                <tr class=""info"">
                    <td>
                        序号
                    </td>
                    <td>
                        标题
                    </td>
                    <td>
                        类别
                    </td>
                    <td>
                       文章标签
                    </td>
                    <td>
                        访问量
                    </td>
                    <td>
                        变更时间
                    </td>
                    <td>
                        状态
                    </td>
                    <td>
                        修改
                    </td>
                    <td>
                        永久删除
                    </td>
                </tr>
");


            
            #line 50 "..\..\Views\BlogManager\ArticleManger.cshtml"
                for (int i = 0; i < Model.Count; i++)
               { 
                   
                   

            
            #line default
            #line hidden

            
            #line 54 "..\..\Views\BlogManager\ArticleManger.cshtml"
WriteLiteral("                   <tr ");

            
            #line default
            #line hidden
            
            #line 54 "..\..\Views\BlogManager\ArticleManger.cshtml"
                        if ((i % 2) == 0)
                       {

            
            #line default
            #line hidden
WriteLiteral("                           ");

WriteLiteral("class=\"\'firseTd\'\"\r\n");


            
            #line 57 "..\..\Views\BlogManager\ArticleManger.cshtml"
                       }
            
            #line default
            #line hidden
WriteLiteral("   >\r\n                          \r\n                          \r\n                   " +
" <td>\r\n                        ");


            
            #line 61 "..\..\Views\BlogManager\ArticleManger.cshtml"
                    Write(i + 1);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                       \r\n");


            
            #line 65 "..\..\Views\BlogManager\ArticleManger.cshtml"
                         if (Model[i].Title.Length > 8)
                        {
                            var title = Model[i].Title.Substring(0, 5);
                           
                         

            
            #line default
            #line hidden
WriteLiteral("                           <a href=\"#\" title=\"");


            
            #line 70 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                         Write(Model[i].Title);

            
            #line default
            #line hidden
WriteLiteral("\"> ");


            
            #line 70 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                                            Write(title + "...");

            
            #line default
            #line hidden
WriteLiteral("</a> \r\n");


            
            #line 71 "..\..\Views\BlogManager\ArticleManger.cshtml"
                    
                        }
                        else
                        {
                     

            
            #line default
            #line hidden
WriteLiteral("                           <a href=\"#\" title=\"");


            
            #line 76 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                         Write(Model[i].Title);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 76 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                                          Write(Model[i].Title);

            
            #line default
            #line hidden
WriteLiteral("</a> \r\n");


            
            #line 77 "..\..\Views\BlogManager\ArticleManger.cshtml"
                       
                        }  

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                    <td>\r\n                        ");


            
            #line 81 "..\..\Views\BlogManager\ArticleManger.cshtml"
                   Write(Model[i].ArticleTypeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n");


            
            #line 84 "..\..\Views\BlogManager\ArticleManger.cshtml"
                         foreach (var item in Model[i].ArticleTags)
                        { 
                            
            
            #line default
            #line hidden
            
            #line 86 "..\..\Views\BlogManager\ArticleManger.cshtml"
                       Write(item.Value);

            
            #line default
            #line hidden

WriteLiteral(" <br />\r\n");


            
            #line 87 "..\..\Views\BlogManager\ArticleManger.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                    <td>\r\n                        ");


            
            #line 90 "..\..\Views\BlogManager\ArticleManger.cshtml"
                   Write(Model[i].ReadCount);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                       ");


            
            #line 93 "..\..\Views\BlogManager\ArticleManger.cshtml"
                  Write(Model[i].LastUpdate);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                        ");


            
            #line 96 "..\..\Views\BlogManager\ArticleManger.cshtml"
                   Write(Html.ActionLink(Model[i].IsShow ? "显示" : "隐藏", "SetArticleIsShow", new { @articleId = Model[i].Id, @pageIndex = Model.PageIndex }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td>\r\n                          " +
"  <a href=\'");


            
            #line 99 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                Write(Url.Action("UpdateArticle", "BlogManager", new { @articleId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\'  >修改</a> \r\n                    </td>\r\n                    <td>\r\n               " +
"          <a href=\'javascript:void(0);\'  ref=\"");


            
            #line 102 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                                        Write(Url.Action("DeleteArticle"));

            
            #line default
            #line hidden
WriteLiteral("?articleId=");


            
            #line 102 "..\..\Views\BlogManager\ArticleManger.cshtml"
                                                                                               Write(Model[i].Id);

            
            #line default
            #line hidden
WriteLiteral(" \" onclick=\"DeleteArticle(this)\">删除</a> \r\n                    </td>\r\n            " +
"    </tr>\r\n");


            
            #line 105 "..\..\Views\BlogManager\ArticleManger.cshtml"
               } 

            
            #line default
            #line hidden

            
            #line 106 "..\..\Views\BlogManager\ArticleManger.cshtml"
                  if (Model.Count <= 0)
                 { 

            
            #line default
            #line hidden
WriteLiteral("                       <tr  class=\"firseTd\"><td colspan=\"9\" style=\"text-align:cen" +
"ter;\">暂无数据</td></tr>\r\n");


            
            #line 109 "..\..\Views\BlogManager\ArticleManger.cshtml"
                       
                 } 

            
            #line default
            #line hidden
WriteLiteral("                <tfoot>\r\n                    <tr>\r\n                        <td co" +
"lspan=\"9\">\r\n                            共有 ");


            
            #line 114 "..\..\Views\BlogManager\ArticleManger.cshtml"
                          Write(Model.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条记录\r\n                        </td>\r\n                    </tr>\r\n                <" +
"/tfoot>\r\n            </table>\r\n            <!-- 分页/开始 --> \r\n               ");


            
            #line 120 "..\..\Views\BlogManager\ArticleManger.cshtml"
          Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
WriteLiteral(" ");


        }
    }
}
#pragma warning restore 1591
