#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/MyAccount.cshtml")]
    public partial class MyAccount : System.Web.Mvc.WebViewPage<Cotide.Web.Controllers.BlogManager.ViewModel.UserAccountModel>
    {
        public MyAccount()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\MyAccount.cshtml"
  
    ViewBag.Title = "MyAccount";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden


DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\BlogManager\MyAccount.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\BlogManager\MyAccount.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<legend>\r\n    <h4>\r\n        个人信息</h4>\r\n</legend>\r\n");


            
            #line 14 "..\..\Views\BlogManager\MyAccount.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 15 "..\..\Views\BlogManager\MyAccount.cshtml"
 using (Html.BeginForm("MyAccount", "BlogManager", FormMethod.Post, new { @id = "UpdateUserAccount", @enctype = "multipart/form-data" }))
{ 

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        ");


            
            #line 18 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationExSummary("UpdateUserAccount"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            头像 ：</label>\r\n        <img style=\"width: 13" +
"0px; height: 130px;\" src=\"");


            
            #line 23 "..\..\Views\BlogManager\MyAccount.cshtml"
                                                  Write(Model.ImgHead);

            
            #line default
            #line hidden
WriteLiteral("\"></img>\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <input type=\"file\" name=\"file\" />\r\n    </p>\r\n");



WriteLiteral("     <p class=\"text-info\">\r\n       \r\n             <i class=\"icon-user\"></i>  ");


            
            #line 30 "..\..\Views\BlogManager\MyAccount.cshtml"
                                   Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral("\r\n           \r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            中文名称 ：</label>\r\n        ");


            
            #line 36 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.RealName, new
   {
       @style = "width: 130px; color: Silver;",
       @title = "中文名称",
       @maxlength = "20",
       @placeholder = "请输入中文名称(必填)"
   }, new ValidateOption()
   {
       EmptyMsg = "您还没输入中文名称",
       Description =
           "中文名称格式:1-20位字符",
       Min = 1,
       Max = 20,
       RangeMsg = "请确保中文名在1-20位字符内"
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 51 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.RealName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            英文名 ：</label>\r\n        ");


            
            #line 56 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.EnRealName, new
   {
       @style = "width: 130px; color: Silver;",
       @title = "英文名称",
       @maxlength = "20",
   }, new ValidateOption()
   {
       Min = 0,
       Max = 20,
       RangeMsg = "请确保中文名在0-20位字符内",
       IsEmpty = true
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 68 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.EnRealName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            手机号码 ：</label>\r\n        ");


            
            #line 73 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.Phone, new
   {
       @style = "width: 130px; color: Silver;",
       @title = "手机号码",
       @maxlength = "15",
   }, new ValidateOption()
   {
       Regex = @"/^1[3|4|5|8][0-9]\d{4,8}$/",
       RegexMsg = "请确保手机号码格式正确",
       Description = "手机号码仅自己可见",
       IsEmpty = true
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 85 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.Phone));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");


            
            #line 87 "..\..\Views\BlogManager\MyAccount.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        <label>\r\n            性别 ：</label>\r\n        ");


            
            #line 91 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.DropDownListFor(x => x.Sex, new List<SelectListItem>()
                                      {
                                           new SelectListItem() {Text = @"-请选择性别-", Value = "2"},
                                           new SelectListItem() {Text = @"男", Value = "0" },
                                           new SelectListItem() {Text = @"女", Value = "1" } 
                                      }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <h4>\r\n        博客信息</h4>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            博客名称 ：</label>\r\n        ");


            
            #line 103 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.BlogName, new
   {
       @style = "width: 130px; color: Silver;",
       @title = "博客名称",
       @maxlength = "50",
       @placeholder = "请输入博客名称(必填)"
   }, new ValidateOption()
   {
       EmptyMsg = "您还没输入博客名称",
       Description =
           "博客名称格式:1-50位字符",
       Min = 1,
       Max = 50,
       RangeMsg = "请确保博客名称在1-50位字符内"
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 118 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.BlogName));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            博客描述 ：</label>\r\n        ");


            
            #line 123 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextAreaExFor(x => x.BlogDesc, new
   {
       @style = "width: 500px; color: Silver;rows : 8",
       @title = "博客描述",
       @maxlength = "255",
       @placeholder = "请输入博客描述"
   }, new ValidateOption()
   {
       Max = 255,
       RangeMsg = "请确保博客描述在0-255位字符内",
       IsEmpty = true
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 135 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.BlogDesc));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <h4>\r\n        其他</h4>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            Email ：</label>\r\n        ");


            
            #line 142 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.Emali, new
   {
       @style = "width: 130px; color: Silver;",
       @title = "Email",
       @maxlength = "30",
   }, new ValidateOption()
   {
       Regex = @"/^([a-zA-Z0-9_-])+@([a-zA-Z0-9_-])+((\.[a-zA-Z0-9_-]{2,3}){1,2})$/",
       RegexMsg = "请确Email格式正确",
       IsEmpty = true
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 153 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.Emali));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <label>\r\n            个人微博 ：</label>\r\n        ");


            
            #line 158 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.TextBoxExFor(x => x.WeiBoUrl, new
   {
       @style = "width: 255px; color: Silver;",
       @title = "个人微博",
       @maxlength = "200",
   }, new ValidateOption()
   {
       Regex = @"/^((http|https):\/\/)?((weibo.com|WEIBO.COM)\/+[a-zA-Z0-9_-]+$)/",
       RegexMsg = "请确个人微博格式正确",
       IsEmpty = true
   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 169 "..\..\Views\BlogManager\MyAccount.cshtml"
   Write(Html.ValidationMessageExFor(x => x.WeiBoUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p> \r\n");



WriteLiteral("    <p>\r\n        <button type=\"submit\" class=\"btn btn-primary\">\r\n            发布</" +
"button>\r\n    </p>\r\n");


            
            #line 175 "..\..\Views\BlogManager\MyAccount.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
