#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 12 "..\..\Views\BlogManager\ProjectType.cshtml"
    using Cotide.Framework.Collections;
    
    #line default
    #line hidden
    
    #line 13 "..\..\Views\BlogManager\ProjectType.cshtml"
    using Cotide.Web.Controllers.BlogManager.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/ProjectType.cshtml")]
    public partial class ProjectType : System.Web.Mvc.WebViewPage<PagedList<ProjectTypeModel>>
    {
        public ProjectType()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\ProjectType.cshtml"
  
    ViewBag.Title = "ProjectType";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 6 "..\..\Views\BlogManager\ProjectType.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\BlogManager\ProjectType.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n    ");


            
            #line 8 "..\..\Views\BlogManager\ProjectType.cshtml"
Write(Html.StyleSheet("lib/jquery-ui-1.8.11.custom.css"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 9 "..\..\Views\BlogManager\ProjectType.cshtml"
Write(Html.JavaScript("lib/jquery-ui.min.js"));

            
            #line default
            #line hidden
WriteLiteral("    \r\n    ");


            
            #line 10 "..\..\Views\BlogManager\ProjectType.cshtml"
Write(Html.JavaScript("cotide/cotide.dialog.init.js"));

            
            #line default
            #line hidden
WriteLiteral("   \r\n");


});

WriteLiteral("\r\n");




WriteLiteral(@" <script type=""text/javascript"">
     function DeleteProjectType(obj) {
         if (confirm('是否删除该作品类型')) {
             location = $(obj).attr(""ref"");
         }
     }
     function UpdateProjectType(obj) {
         var url = $(obj).attr(""ref"");
         cotide.dialog.open(url, ""修改作品类型"", 480, 230, function () {
             location = '");


            
            #line 24 "..\..\Views\BlogManager\ProjectType.cshtml"
                    Write(Url.Action("ProjectType", "BlogManager"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n         });\r\n     } \r\n  </script> \r\n <legend>\r\n        <h4>\r\n            作品类" +
"别管理</h4>\r\n    </legend>\r\n    <h4>\r\n        新增作品类别</h4>\r\n");


            
            #line 34 "..\..\Views\BlogManager\ProjectType.cshtml"
     using (Html.BeginForm("ProjectType", "BlogManager", FormMethod.Post, new { id = "AddProjectTypeFrom" }))
       { 

            
            #line default
            #line hidden
WriteLiteral(@"    <p>
        <label class=""required"">
            作品类型名称 ：</label>
        <input id=""projectTypeName"" name=""projectTypeName"" style=""width: 500px;"" class=""half""
            type=""text"" />
        <button type=""submit"" class=""btn btn-primary"">
            保存
        </button>
    </p>
");


            
            #line 45 "..\..\Views\BlogManager\ProjectType.cshtml"
       } 

            
            #line default
            #line hidden
WriteLiteral(@"    <h4>
        您已拥有的文章类别</h4>
    <!-- 文章类别列表/开始 -->
   <table  class=""table  table-hover"">
                <tr class=""info"">
            <td>
                序号
            </td>
            <td>
                项目类别名称
            </td>
            <td>
                状态
            </td>
            <td>
                修改
            </td>
            <td>
                彻底删除
            </td>
        </tr>
");


            
            #line 67 "..\..\Views\BlogManager\ProjectType.cshtml"
         for (int i = 0; i < Model.Count; i++)
            { 

            
            #line default
            #line hidden

            
            #line 69 "..\..\Views\BlogManager\ProjectType.cshtml"
WriteLiteral("        <tr  ");

            
            #line default
            #line hidden
            
            #line 69 "..\..\Views\BlogManager\ProjectType.cshtml"
              if ((i % 2) == 0)
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("class=\"\'firseTd\'\"\r\n");


            
            #line 72 "..\..\Views\BlogManager\ProjectType.cshtml"
                 }
            
            #line default
            #line hidden
WriteLiteral(" >\r\n            <td>\r\n                ");


            
            #line 74 "..\..\Views\BlogManager\ProjectType.cshtml"
            Write(i+1);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 77 "..\..\Views\BlogManager\ProjectType.cshtml"
           Write(Model[i].TypeName);

            
            #line default
            #line hidden
WriteLiteral("  \r\n            </td>\r\n            <td>\r\n                ");


            
            #line 80 "..\..\Views\BlogManager\ProjectType.cshtml"
           Write(Html.ActionLink(Model[i].IsShow ? "显示" : "隐藏", "SetProjectTypeIsShow", new { @projectTypeId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n            </td>\r\n            <td>\r\n                <a ref=\'");


            
            #line 83 "..\..\Views\BlogManager\ProjectType.cshtml"
                   Write(Url.Action("UpdateProjectType", "BlogManager", new { @projectTypeId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\' \r\n                   href=\"javascript:void(0);\"\r\n                          oncl" +
"ick=\"UpdateProjectType(this)\"   >修改</a>\r\n            </td>\r\n            <td>\r\n  " +
"              <a href=\'javascript:void(0);\' ref=\"");


            
            #line 88 "..\..\Views\BlogManager\ProjectType.cshtml"
                                              Write(Url.Action("DeleteProjectType"));

            
            #line default
            #line hidden
WriteLiteral("?projectTypeId=");


            
            #line 88 "..\..\Views\BlogManager\ProjectType.cshtml"
                                                                                             Write(Model[i].Id);

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n                    onclick=\"DeleteProjectType(this)\">删除</a>\r\n            </t" +
"d>\r\n        </tr>\r\n");


            
            #line 92 "..\..\Views\BlogManager\ProjectType.cshtml"
        } 

            
            #line default
            #line hidden

            
            #line 93 "..\..\Views\BlogManager\ProjectType.cshtml"
          if (Model.Count <= 0)
         {

            
            #line default
            #line hidden
WriteLiteral("             <tr class=\"firseTd\">\r\n                 <td colspan=\"6\" style=\"text-a" +
"lign: center;\">\r\n                     暂无数据\r\n                 </td>\r\n            " +
" </tr>\r\n");


            
            #line 100 "..\..\Views\BlogManager\ProjectType.cshtml"
         }

            
            #line default
            #line hidden
WriteLiteral("        <tfoot>\r\n            <tr>\r\n                <td colspan=\"6\">\r\n            " +
"        共有 ");


            
            #line 104 "..\..\Views\BlogManager\ProjectType.cshtml"
                  Write(Model.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条记录\r\n                </td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n " +
"   <!-- 分页/开始 -->\r\n    \r\n         ");


            
            #line 111 "..\..\Views\BlogManager\ProjectType.cshtml"
    Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n ");


        }
    }
}
#pragma warning restore 1591
