#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\BlogManager\Project.cshtml"
    using Cotide.Framework.Collections;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\BlogManager\Project.cshtml"
    using Cotide.Web.Controllers.BlogManager.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/Project.cshtml")]
    public partial class Project : System.Web.Mvc.WebViewPage<PagedList<ProjectModel>>
    {
        public Project()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\Project.cshtml"
  
    ViewBag.Title = "Project";
    Layout = "~/Views/Shared/_BlogManagerLayout.cshtml";


            
            #line default
            #line hidden



WriteLiteral(@"  <script type=""text/javascript"">
      function DeleteProject(obj) {
          if (confirm('是否删除该作品')) {
              location = $(obj).attr(""ref"");
          }
      } 
 </script>

  <legend>
        <h4>
            您已拥有的作品</h4>
    </legend>
<table  class=""table  table-hover"">
                <tr class=""info"">
            <td>
                序号
            </td>
            <td>
                作品标题
            </td>
            <td>
                作品类型
            </td>
            <td>
                状态
            </td>
              <td>
                排序
            </td>
            <td>
                变更时间
            </td>
            <td>
                修改
            </td>
            <td>
                彻底删除
            </td>
        </tr>
");


            
            #line 47 "..\..\Views\BlogManager\Project.cshtml"
          for (int i = 0; i < Model.Count; i++)
            { 

            
            #line default
            #line hidden

            
            #line 49 "..\..\Views\BlogManager\Project.cshtml"
WriteLiteral("        <tr  ");

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\BlogManager\Project.cshtml"
              if ((i % 2) == 0)
                 {

            
            #line default
            #line hidden
WriteLiteral("                     ");

WriteLiteral("class=\"\'firseTd\'\"\r\n");


            
            #line 52 "..\..\Views\BlogManager\Project.cshtml"
                 }
            
            #line default
            #line hidden
WriteLiteral(" >\r\n            <td>\r\n                ");


            
            #line 54 "..\..\Views\BlogManager\Project.cshtml"
            Write(i+1);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 57 "..\..\Views\BlogManager\Project.cshtml"
           Write(Model[i].ProjectName);

            
            #line default
            #line hidden
WriteLiteral(" \r\n            </td>\r\n            <td>\r\n                 ");


            
            #line 60 "..\..\Views\BlogManager\Project.cshtml"
            Write(Model[i].TypeName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                ");


            
            #line 63 "..\..\Views\BlogManager\Project.cshtml"
           Write(Html.ActionLink(Model[i].IsShow ? "显示" : "隐藏", "SetProjectIsShow", new { @projectId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n             <td>\r\n                ");


            
            #line 66 "..\..\Views\BlogManager\Project.cshtml"
           Write(Model[i].Sort);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <td>\r\n                  ");


            
            #line 69 "..\..\Views\BlogManager\Project.cshtml"
             Write(Model[i].LastDateTime);

            
            #line default
            #line hidden
WriteLiteral(" \r\n            </td>\r\n            <td>\r\n                <a href=\'");


            
            #line 72 "..\..\Views\BlogManager\Project.cshtml"
                    Write(Url.Action("UpdateProject", "BlogManager", new { @projectId = Model[i].Id }));

            
            #line default
            #line hidden
WriteLiteral("\'>\r\n                    修改</a>\r\n            </td>\r\n            <td>\r\n            " +
"    <a href=\'javascript:void(0);\' ref=\"");


            
            #line 76 "..\..\Views\BlogManager\Project.cshtml"
                                              Write(Url.Action("DeleteProject"));

            
            #line default
            #line hidden
WriteLiteral("?projectId=");


            
            #line 76 "..\..\Views\BlogManager\Project.cshtml"
                                                                                     Write(Model[i].Id);

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n                    onclick=\"DeleteProject(this)\">删除</a>\r\n            </td>\r\n" +
"        </tr>\r\n");


            
            #line 80 "..\..\Views\BlogManager\Project.cshtml"
         } 

            
            #line default
            #line hidden

            
            #line 81 "..\..\Views\BlogManager\Project.cshtml"
         if (Model.Count <= 0)
           { 

            
            #line default
            #line hidden
WriteLiteral("        <tr class=\"firseTd\">\r\n            <td colspan=\"8\" style=\"text-align: cent" +
"er;\">\r\n                暂无数据\r\n            </td>\r\n        </tr>\r\n");


            
            #line 88 "..\..\Views\BlogManager\Project.cshtml"
        } 

            
            #line default
            #line hidden
WriteLiteral("        <tfoot>\r\n            <tr>\r\n                <td colspan=\"8\">\r\n            " +
"        共有 ");


            
            #line 92 "..\..\Views\BlogManager\Project.cshtml"
                  Write(Model.TotalCount);

            
            #line default
            #line hidden
WriteLiteral(" 条记录\r\n                </td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n " +
"   <!-- 分页/开始 -->\r\n     ");


            
            #line 98 "..\..\Views\BlogManager\Project.cshtml"
Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
WriteLiteral("\r\n  ");


        }
    }
}
#pragma warning restore 1591
