#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\BlogManager\UpdateAd.cshtml"
    using Cotide.Web.Controllers.BlogManager.ViewModel.Ad;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/UpdateAd.cshtml")]
    public partial class UpdateAd : System.Web.Mvc.WebViewPage<UpdateAdViewModel>
    {
        public UpdateAd()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\UpdateAd.cshtml"
  
    ViewBag.Title = "UpdateArticleType";
    Layout = "~/Views/Shared/_DialogLayout.cshtml";


            
            #line default
            #line hidden



DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\BlogManager\UpdateAd.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 9 "..\..\Views\BlogManager\UpdateAd.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<div class=\"container-fluid\">\r\n<p>\r\n    ");


            
            #line 13 "..\..\Views\BlogManager\UpdateAd.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n</div>\r\n<div class=\"container-fluid\">\r\n");


            
            #line 17 "..\..\Views\BlogManager\UpdateAd.cshtml"
     using (Html.BeginForm("UpdateAd", "BlogManager", FormMethod.Post, new { @Id = "UpdateAdFrom", @enctype = "multipart/form-data" }))
    { 

            
            #line default
            #line hidden
WriteLiteral("             <p>\r\n        ");


            
            #line 20 "..\..\Views\BlogManager\UpdateAd.cshtml"
   Write(Html.ValidationExSummary("AdAdFrom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 21 "..\..\Views\BlogManager\UpdateAd.cshtml"
   Write(Html.HiddenFor(x=>x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>");



WriteLiteral("<p>\r\n       <img style=\"width: 50px;height:50px;\" src=\"");


            
            #line 23 "..\..\Views\BlogManager\UpdateAd.cshtml"
                                             Write(Model.SmallAdImg);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n     <br/>\r\n          <label class=\"required\">\r\n            广告图片  (940px X " +
"450px) ：</label> \r\n            <input type=\"file\" name=\"AdImg\" id=\"AdImg\" /> \r\n " +
"        </p>\r\n");



WriteLiteral("    <p>\r\n        <label class=\"required\">\r\n            广告名称 ：</label>\r\n\r\n        " +
"  ");


            
            #line 33 "..\..\Views\BlogManager\UpdateAd.cshtml"
     Write(Html.TextBoxExFor(x=>x.AdName, new
     {
         @style = "width: 500px; color: Silver;",
         @title = "广告名称",
         @maxlength = "50",
         @placeholder = "请输入广告名称(必填)"
     }, new ValidateOption()
     {
         EmptyMsg = "您还没输入广告名称",
         Description =
             "文章类别格式:1-50位字符",
         Min = 1,
         Max = 50,
         RangeMsg = "请确保文章类别在1-50位字符内"
     }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 48 "..\..\Views\BlogManager\UpdateAd.cshtml"
   Write(Html.ValidationMessageExFor(x=>x.AdName));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </p>\r\n");



WriteLiteral("     <p>\r\n         <label class=\"required\">\r\n            广告类型 ：</label>\r\n        " +
" ");


            
            #line 53 "..\..\Views\BlogManager\UpdateAd.cshtml"
    Write(Html.DropDownListFor(x=>x.AdType, new List<SelectListItem>()
                                      {
                                          
                                          new SelectListItem()
                                              {
                                                  Selected = true,
                                                  Text = @"首页",
                                                  Value = "0"
                                              }
                                      }));

            
            #line default
            #line hidden
WriteLiteral("\r\n     </p>    \r\n");



WriteLiteral("         <p>\r\n         <label class=\"required\">\r\n            广告描述 ：</label> \r\n   " +
"             ");


            
            #line 67 "..\..\Views\BlogManager\UpdateAd.cshtml"
           Write(Html.TextBoxExFor(x=>x.AdDesc, new
           {
               @style = "width: 500px; color: Silver;",
               @title = "广告描述",
               @maxlength = "100",
               @placeholder = "请输入广告描述"
           }, new ValidateOption()
           {
               Min = 0,
               Max = 100,
               RangeMsg = "请确保广告描述在0-100位字符内",
               IsEmpty = true
           }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 80 "..\..\Views\BlogManager\UpdateAd.cshtml"
   Write(Html.ValidationMessageExFor(x=>x.AdDesc));

            
            #line default
            #line hidden
WriteLiteral(" \r\n         \r\n         </p>\r\n");



WriteLiteral("          <p>\r\n    \r\n      <label class=\"required\" for=\"password\">\r\n            前" +
"端显示 ：\r\n        </label>\r\n        ");


            
            #line 88 "..\..\Views\BlogManager\UpdateAd.cshtml"
   Write(Html.DropDownListFor(x=>x.IsShow, new List<SelectListItem>()
                                                                                   {
                                                                                       new SelectListItem()
                                                                                           {
                                                                                               Text = @"公开",
                                                                                               Value = "true"
                                                                                           },
                                                                                       new SelectListItem()
                                                                                           {
                                                                                               Text = @"仅自己可见",
                                                                                               Value = "false"
                                                                                           }
                                                                                   }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("             <p>\r\n    \r\n      <label class=\"required\"  >\r\n            排序 ：\r\n     " +
"   </label>\r\n    ");


            
            #line 107 "..\..\Views\BlogManager\UpdateAd.cshtml"
Write(Html.TextBoxFor(x=>x.Sort, new
{
    @style = "width: 150px; color: Silver;",
    @title = "排序",
    @placeholder = "请输入排序"
}));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n      <button type=\"submit\" class=\"btn btn-primary\"> 保存 </button>\r\n    <" +
"/p>\r\n");


            
            #line 117 "..\..\Views\BlogManager\UpdateAd.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<!-- 修改面板 -->\r\n");


        }
    }
}
#pragma warning restore 1591
