#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.BlogManager
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogManager/UpdateArticleType.cshtml")]
    public partial class UpdateArticleType : System.Web.Mvc.WebViewPage<Cotide.Web.Controllers.BlogManager.ViewModel.ArticleTypeModel>
    {
        public UpdateArticleType()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
  
    ViewBag.Title = "UpdateArticleType";
    Layout = "~/Views/Shared/_DialogLayout.cshtml";


            
            #line default
            #line hidden


DefineSection("Head", () => {

WriteLiteral("\r\n    ");


            
            #line 7 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
Write(Html.StyleSheet("validate/pagevalidator.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 8 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
Write(Html.JavaScript("validate/pagevalidator_v2.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


});

WriteLiteral("\r\n<div class=\"container-fluid\">\r\n<p>\r\n    ");


            
            #line 12 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
Write(ViewData["alert"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n</div>\r\n<div class=\"container-fluid\">\r\n");


            
            #line 16 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
     using (Html.BeginForm("UpdateArticleType", "BlogManager", FormMethod.Post, new { @Id = "UpdateArticleTypeFrom" }))
    { 

            
            #line default
            #line hidden
WriteLiteral("        <p>\r\n            ");


            
            #line 19 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
       Write(Html.ValidationExSummary("UpdateArticleTypeFrom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n");



WriteLiteral("        <p>\r\n            <label class=\"required\">\r\n                文章类别名称 ：</labe" +
"l>\r\n            ");


            
            #line 24 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
       Write(Html.TextBoxExFor(x => x.TypeName, new
             {
                 @style = "width: 205px; color: Silver;",
                 @title = "文章类别名称",
                 @maxlength = "30",
                 @placeholder = "请输入文章类别名称(必填)"
             }, new ValidateOption()
             {
                 EmptyMsg = "您还没输入文章类别",
                 Description =
                     "文章类别格式:1-30位字符",
                 Min = 1,
                 Max = 255,
                 RangeMsg = "请确保文章类别在1-30位字符内"
             }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 39 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
       Write(Html.ValidationMessageExFor(x => x.TypeName));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 40 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
       Write(Html.HiddenFor(x => x.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n");



WriteLiteral("        <p>\r\n            <label class=\"required\">\r\n                状态 ：</label>\r\n" +
"            ");


            
            #line 45 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
       Write(Html.DropDownListFor(x => x.IsShow, new List<SelectListItem>()
                                                           {
                                                               new SelectListItem(){ Text=@"显示", Value="true"},
                                                                new SelectListItem(){ Text=@"隐藏",Value="false"}
                                                           }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </p>\r\n");



WriteLiteral("        <p>\r\n            <input type=\"submit\" class=\"btn btn-primary\" value=\" 保存 " +
"\" />\r\n        </p> \r\n");


            
            #line 54 "..\..\Views\BlogManager\UpdateArticleType.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<!-- 修改面板 -->\r\n");


        }
    }
}
#pragma warning restore 1591
