#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel.Article;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_AnonymousUserReply.cshtml")]
    public partial class AnonymousUserReply : System.Web.Mvc.WebViewPage<SaveMessageViewModel>
    {
        public AnonymousUserReply()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden


WriteLiteral(" \r\n");


            
            #line 7 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
 using (Html.BeginForm("SaveAnonymousUserMessage", "Blog", FormMethod.Post,
                           new { @id = "SaveMessageFrom"  }))
    {
       

            
            #line default
            #line hidden
WriteLiteral("<p>\r\n \r\n            <div id=\"msgTip\">\r\n</div>\r\n    ");


            
            #line 15 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
Write(Html.HiddenFor(x => x.ArticleId));

            
            #line default
            #line hidden
WriteLiteral(" \r\n      <p>昵称:</p>\r\n    ");


            
            #line 17 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
Write(Html.TextBoxFor(x => x.NickName, new { @size = "22", @tabindex = "1", @placeholder = "昵称" }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n</p>\r\n");



WriteLiteral("<p>\r\n <p>Email:</p>\r\n    ");


            
            #line 21 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
Write(Html.TextBoxFor(x => x.Email, new { @size = "22", @tabindex = "2", @placeholder = "请输入Email(非必填)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");



WriteLiteral("<p>\r\n <p>个人网站:</p>\r\n    ");


            
            #line 25 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
Write(Html.TextBoxFor(x => x.WebSiteUrl, new
{
    @size = "22",
    @tabindex = "3",
    @placeholder = "请输入个人网站(非必填)"
}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n</p>\r\n");



WriteLiteral("<p>\r\n<p>评论内容:</p>\r\n    ");


            
            #line 34 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
Write(Html.TextAreaFor(x => x.Comment, new
{
    @rows = "10",
    @style = "width: 90%;",
    @placeholder = "请输入评论内容",
    @tabindex = "4"
}));

            
            #line default
            #line hidden
WriteLiteral(" \r\n</p>\r\n");



WriteLiteral("<p>\r\n    <button type=\"submit\" class=\"btn btn-primary\">\r\n        <i class=\"icon-u" +
"ser\"></i>评论</button>\r\n</p> \r\n");


            
            #line 46 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
    } 

            
            #line default
            #line hidden
WriteLiteral(@"
<script type=""text/javascript"">
    $(function () { 
        $(""#SaveMessageFrom"").ajaxPostForm(function() { 
            // 评论前验证
            if ($.trim($(""#NickName"").val()) == """") {  
                cotide.dialog.showResultMsg(""msgTip"", ""请输入您的评论内容!"", ""info"");
                return false; 
            } 
            // 评论前验证
            if ($.trim($(""#Comment"").val()) == """") { 
                cotide.dialog.showResultMsg(""msgTip"", ""请输入评论内容!"", ""info"");
                return false;
             }
            return true;
        }, function () {
            // 评论成功
            $(""#NickName"").val("""");  
            $(""#Email"").val("""");  
            $(""#WebSiteUrl"").val("""");  
            $(""#Comment"").val("""");  
            cotide.dialog.showResultMsg(""msgTip"", ""评论成功!"", ""success"");
            $(""#articleCommentPanl"").ajaxLoadData(""");


            
            #line 69 "..\..\Views\Blog\_AnonymousUserReply.cshtml"
                                              Write(Url.Action("ArticleComment", "Blog", new { @id = Model.ArticleId }));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n        },function (e) { \r\n            // 评论失败\r\n            cotide.dialog.sh" +
"owResultMsg(\"msgTip\", e.Data, \"error\");\r\n        });\r\n    })\r\n</script>\r\n");


        }
    }
}
#pragma warning restore 1591
