#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_ArticleDate.cshtml")]
    public partial class ArticleDate : System.Web.Mvc.WebViewPage<IList<Cotide.Web.Controllers.Blog.ViewModel.ArticleDateViewModel>>
    {
        public ArticleDate()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Blog\_ArticleDate.cshtml"
WriteLiteral("<legend>  <lable>  文章</lable> </legend> ");

            
            #line default
            #line hidden
            
            #line 2 "..\..\Views\Blog\_ArticleDate.cshtml"
                                         if (Model != null && Model.Count > 0)
   {
            
            #line default
            #line hidden

            
            #line 3 "..\..\Views\Blog\_ArticleDate.cshtml"
    WriteLiteral("  <ul class=\"nav nav-pills nav-stacked\">   ");

            
            #line default
            #line hidden
            
            #line 3 "..\..\Views\Blog\_ArticleDate.cshtml"
                                                foreach (var item in Model)
       {
            
            #line default
            #line hidden
WriteLiteral("  <li><a href=\"");


            
            #line 4 "..\..\Views\Blog\_ArticleDate.cshtml"
                  Write(Url.Action("Articles", "Blog", new { @year = item.Year, @mouth=item.Mouth}));

            
            #line default
            #line hidden
WriteLiteral("\"> ");


            
            #line 4 "..\..\Views\Blog\_ArticleDate.cshtml"
                                                                                                 Write(item.Year);

            
            #line default
            #line hidden
WriteLiteral("  ");


            
            #line 4 "..\..\Views\Blog\_ArticleDate.cshtml"
                                                                                                             Write(item.Mouth);

            
            #line default
            #line hidden
WriteLiteral(" 月 ( ");


            
            #line 4 "..\..\Views\Blog\_ArticleDate.cshtml"
                                                                                                                             Write(item.Count);

            
            #line default
            #line hidden
WriteLiteral(" ) </a></li>   ");


            
            #line 4 "..\..\Views\Blog\_ArticleDate.cshtml"
                                                                                                                                                            } 

            
            #line default
            #line hidden
WriteLiteral("</ul> ");


            
            #line 5 "..\..\Views\Blog\_ArticleDate.cshtml"
      }
   else
   { 

            
            #line default
            #line hidden
WriteLiteral("<p style=\"text-align: center;\">\r\n    暂无文章\r\n</p>\r\n");


            
            #line 11 "..\..\Views\Blog\_ArticleDate.cshtml"
 } 

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
