#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_ArticleType.cshtml")]
    public partial class ArticleType : System.Web.Mvc.WebViewPage<IList<Cotide.Web.Controllers.Blog.ViewModel.ArticleTypeViewModel>>
    {
        public ArticleType()
        {
        }
        public override void Execute()
        {

WriteLiteral("<legend>  <lable>  文章分类</lable> </legend>\r\n");


            
            #line 3 "..\..\Views\Blog\_ArticleType.cshtml"
  if (Model != null && Model.Count > 0)
 {
            
            #line default
            #line hidden
WriteLiteral("  <ul class=\"nav nav-pills nav-stacked\">     \r\n");


            
            #line 5 "..\..\Views\Blog\_ArticleType.cshtml"
  foreach (var item in Model)
 {
            
            #line default
            #line hidden
WriteLiteral("  <li><a href=\"");


            
            #line 6 "..\..\Views\Blog\_ArticleType.cshtml"
            Write(Url.Action("ArticleType", "Blog", new { @id = item.TypeId }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 6 "..\..\Views\Blog\_ArticleType.cshtml"
                                                                                  Write(item.TypeName);

            
            #line default
            #line hidden
WriteLiteral("\">  ");


            
            #line 6 "..\..\Views\Blog\_ArticleType.cshtml"
                                                                                                    Write(item.TypeName);

            
            #line default
            #line hidden
WriteLiteral("  </a></li> ");


            
            #line 6 "..\..\Views\Blog\_ArticleType.cshtml"
                                                                                                                                   }
            
            #line default
            #line hidden
WriteLiteral(" </ul>\r\n");


            
            #line 7 "..\..\Views\Blog\_ArticleType.cshtml"
 }
 else
 { 

            
            #line default
            #line hidden
WriteLiteral("    <p style=\"text-align: center;\">\r\n        暂无分类\r\n    </p>\r\n");


            
            #line 13 "..\..\Views\Blog\_ArticleType.cshtml"
 }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
