#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel.Article;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_CommentAnonymousUserReply.cshtml")]
    public partial class CommentAnonymousUserReply : System.Web.Mvc.WebViewPage<SaveMessageReplyViewModel>
    {
        public CommentAnonymousUserReply()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden


WriteLiteral("\r\n<script type=\"text/javascript\">\r\n    $(function() {\r\n        var id = \"");


            
            #line 9 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
             Write(Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral(@""";
        $(""#SaveMessageReplyFrom"" + id).ajaxPostForm(function() {
            var $form = $(""#SaveMessageReplyFrom"" + id);
            var replyComment = $form.find(""textarea[name='ReplyComment']""); 
            var nickName = $form.find(""input[name='ReplyNickName']"");  
            
            // 评论前验证
            if ($.trim(nickName.val()) == """") {  
                cotide.dialog.showResultMsg('");


            
            #line 17 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
                                         Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral("\', \"请输入您的昵称!\", \"info\");\r\n                return false; \r\n            }\r\n         " +
"   if ($.trim(replyComment.val()) == \"\") {\r\n                cotide.dialog.showRe" +
"sultMsg(\'");


            
            #line 21 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
                                         Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral(@"', ""请输入您的评论内容!"", ""info"");
                return false;
            } 
           
            return true;
            
            return true;
        }, function() {
            var $form = $(""#SaveMessageReplyFrom"" + id);
            $form.find(""input[name='ReplyNickName']"").val(""""); 
            $form.find(""input[name='ReplyEmail']"").val("""");  
            $form.find(""input[name='ReplyWebSiteUrl']"").val(""""); 
            $form.find(""textarea[name='ReplyComment']"").val(""""); 
            // 评论成功交互  
            var loadUrl = """);


            
            #line 35 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
                      Write(Url.Action("ArticleComment", "Blog", new { @id = Model.ArticleId }));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            $(\"#articleCommentPanl\").load(loadUrl.urlstamp());\r\n        },fun" +
"ction (e) {\r\n            // 评论失败 \r\n            cotide.dialog.showResultMsg(\'");


            
            #line 39 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
                                     Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral("\', e.Data, \"error\");\r\n        });\r\n    });\r\n</script>\r\n\r\n\r\n<div class=\"row\"  comm" +
"entItem=\"true\"    style=\"display:none;padding-left:20px; background-color: #f5f5" +
"f5; border: 1px solid #000;width:100%;\">\r\n");


            
            #line 46 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
        using (Html.BeginForm("SaveAnonymousUserMessageReply", "Blog", FormMethod.Post,
                           new { @id = "SaveMessageReplyFrom" + Model.FormGuId }))
        {

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        ");


            
            #line 50 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
   Write(Html.HiddenFor(x => x.ArticleId));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 51 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
   Write(Html.HiddenFor(x => x.ReplyMessageId));

            
            #line default
            #line hidden
WriteLiteral(" \r\n          <span><em>评论内容</em></span>\r\n              <div id=\'");


            
            #line 53 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
                   Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral("\' >\r\n</div>\r\n           <p>昵称:</p>\r\n        ");


            
            #line 56 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
   Write(Html.TextBoxFor(x => x.ReplyNickName, new { @size = "22", @tabindex = "1", @placeholder = "请输入昵称" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n         <p>Email:</p>\r\n        ");


            
            #line 60 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
   Write(Html.TextBoxFor(x => x.ReplyEmail, new { @size = "22", @tabindex = "2", @placeholder = "请输入Email(非必填)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n      <p>个人网站:  </p>\r\n        ");


            
            #line 64 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
   Write(Html.TextBoxFor(x => x.ReplyWebSiteUrl, new { @size = "22", @tabindex = "2", @placeholder = "请输入个人网站(非必填)" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n    <p>评论内容:</p>\r\n       ");


            
            #line 69 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
  Write(Html.TextAreaFor(x => x.ReplyComment,
                                           new
                                               {
                                                   @rows = "5",
                                                   @style =
                                               "border: 1px solid #C6C6C6;  resize: none; width: 70%;",
                                                   @tabindex = "4",
                                                   @placeholder = "请输入评论内容"
                                               }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <button type=\"submit\" class=\"btn btn-primary\">\r\n            <i c" +
"lass=\"icon-user\"></i>评论</button>\r\n    </p>\r\n");


            
            #line 83 "..\..\Views\Blog\_CommentAnonymousUserReply.cshtml"
     }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


        }
    }
}
#pragma warning restore 1591
