#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Blog\_CommentUserReply.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel.Article;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_CommentUserReply.cshtml")]
    public partial class CommentUserReply : System.Web.Mvc.WebViewPage<SaveMessageReplyViewModel>
    {
        public CommentUserReply()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\_CommentUserReply.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden


WriteLiteral("<script type=\"text/javascript\">\r\n    $(function() {\r\n        var id = \"");


            
            #line 8 "..\..\Views\Blog\_CommentUserReply.cshtml"
             Write(Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral(@""";
        $(""#SaveMessageReplyFrom"" + id).ajaxPostForm(function() {
            var $form = $(""#SaveMessageReplyFrom"" + id);
            var replyComment = $form.find(""textarea[name='ReplyComment']""); 
            if ($.trim(replyComment.val()) == """") {
                cotide.dialog.showResultMsg('");


            
            #line 13 "..\..\Views\Blog\_CommentUserReply.cshtml"
                                         Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral("\', \"请输入您的评论内容!\", \"info\");\r\n                return false;\r\n            }\r\n        " +
"    return true;\r\n        }, function() {\r\n            // 评论成功交互  \r\n            " +
"var loadUrl = \"");


            
            #line 19 "..\..\Views\Blog\_CommentUserReply.cshtml"
                      Write(Url.Action("ArticleComment", "Blog", new { @id = Model.ArticleId }));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n            $(\"#articleCommentPanl\").load(loadUrl.urlstamp());\r\n        });\r\n" +
"    });\r\n</script>\r\n<div class=\"row\"  commentItem=\"true\"    style=\"display:none;" +
"padding-left:20px;\">\r\n\r\n");


            
            #line 26 "..\..\Views\Blog\_CommentUserReply.cshtml"
      using (Html.BeginForm("SaveMessageReply", "Blog", FormMethod.Post,
                           new { @id = "SaveMessageReplyFrom" + Model.FormGuId }))
        { 

            
            #line default
            #line hidden
WriteLiteral("    <p>\r\n        ");


            
            #line 30 "..\..\Views\Blog\_CommentUserReply.cshtml"
   Write(Html.HiddenFor(x => x.ArticleId));

            
            #line default
            #line hidden
WriteLiteral(" \r\n        ");


            
            #line 31 "..\..\Views\Blog\_CommentUserReply.cshtml"
   Write(Html.HiddenFor(x => x.ReplyMessageId));

            
            #line default
            #line hidden
WriteLiteral("  \r\n            <span><em>评论内容</em></span>\r\n              <div id=\'");


            
            #line 33 "..\..\Views\Blog\_CommentUserReply.cshtml"
                   Write("msgTip" + Model.FormGuId);

            
            #line default
            #line hidden
WriteLiteral("\' >\r\n</div>\r\n        ");


            
            #line 35 "..\..\Views\Blog\_CommentUserReply.cshtml"
   Write(Html.TextAreaFor(x => x.ReplyComment,
                                           new
                                               {
                                                   @rows = "5",
                                                   @style =
                                               "border: 1px solid #C6C6C6;  resize: none; width: 100%;",
                                                   @tabindex = "4",
                                                   @placeholder = "请输入评论内容"
                                               }));

            
            #line default
            #line hidden
WriteLiteral(" \r\n    </p>\r\n");



WriteLiteral("    <p>\r\n        <button type=\"submit\" class=\"btn btn-primary\">\r\n            <i c" +
"lass=\"icon-user\"></i>评论</button>\r\n    </p>\r\n");


            
            #line 49 "..\..\Views\Blog\_CommentUserReply.cshtml"
     } 

            
            #line default
            #line hidden
WriteLiteral(" </div>");


        }
    }
}
#pragma warning restore 1591
