#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_FavoritesUserLink.cshtml")]
    public partial class FavoritesUserLink : System.Web.Mvc.WebViewPage<List<LinkViewModel>>
    {
        public FavoritesUserLink()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden


WriteLiteral(" <ul class=\"nav nav-tabs\" style=\"padding-top: 25px;margin-left:10px;\"> <li>&nbsp;" +
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li> <li class=\"active\"><a href=\"javascript:void(" +
"0);\" ><i class=\"icon-heart\"></i>&nbsp;我的收藏</a> </li>\r\n</ul> <ul class=\"nav nav-p" +
"ills \">  \r\n");


            
            #line 8 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
 foreach (var item in Model)
{
            
            #line default
            #line hidden
WriteLiteral(" <li style=\"width:185px; text-align: center;\"> <a title=\"");


            
            #line 9 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
                                                     Write(item.LinkTxt);

            
            #line default
            #line hidden
WriteLiteral("\" target=\"_blank\" href=\"");


            
            #line 9 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
                                                                                          Write(item.LinkUrl);

            
            #line default
            #line hidden
WriteLiteral("\"> ");


            
            #line 9 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
                                                                                                          Write(item.LinkTxt);

            
            #line default
            #line hidden
WriteLiteral("</a>  </li> ");


            
            #line 9 "..\..\Views\Blog\_FavoritesUserLink.cshtml"
                                                                                                                                        }  

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n ");


        }
    }
}
#pragma warning restore 1591
