#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel.UserTourLog;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_FavoritesUserBlog.cshtml")]
    public partial class FavoritesUserBlog : System.Web.Mvc.WebViewPage<List<UserTourLogViewModel>>
    {
        public FavoritesUserBlog()
        {
        }
        public override void Execute()
        {


WriteLiteral("\r\n<ul class=\"nav nav-tabs\" style=\"padding-top: 25px;margin-left:10px;\">\r\n    <li>" +
"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>\r\n    <li class=\"active\"><a href=\"javas" +
"cript:void(0);\"><i class=\"icon-heart\"></i>&nbsp;我的收藏</a>\r\n    </li>\r\n</ul>\r\n\r\n");


            
            #line 10 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
 if(Model!=null && Model.Count()>0)
{
    

            
            #line default
            #line hidden
WriteLiteral("    <ul class=\"nav nav-pills \" style=\"padding-left: 10px;\">\r\n");


            
            #line 14 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
 foreach(var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("     <li   style=\"margin: 5px 10px 5px 10px;\">\r\n            <div class=\"thumbnail" +
"\" style=\"width: 50px;\">\r\n                <img     style=\"width: 50px; height: 50" +
"px;\" src=\"");


            
            #line 18 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
                                                            Write(item.SmallImgHead);

            
            #line default
            #line hidden
WriteLiteral("\"></img>\r\n              \r\n            </div> \r\n              <div class=\"caption\"" +
" style=\"font-size: 9px;\"> \r\n                 <a href=\"");


            
            #line 22 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
                     Write(Url.Action("Index","Blog",new {@domain=item.Domain}));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 22 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
                                                                            Write(item.BlogName);

            
            #line default
            #line hidden
WriteLiteral("</a>  \r\n                </div> \r\n                <div class=\"caption\" style=\"font" +
"-size: 9px;\"> \r\n                      ");


            
            #line 25 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
                 Write(item.UpdateDate);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div> \r\n        </li> \r\n");


            
            #line 28 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
} 

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


            
            #line 30 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
}else
{

            
            #line default
            #line hidden
WriteLiteral("   <div class=\"container-fluid\" style=\"text-align: center; height:100px;\">暂时没有访问用" +
"户</div>\r\n");


            
            #line 33 "..\..\Views\Blog\_FavoritesUserBlog.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n \r\n ");


        }
    }
}
#pragma warning restore 1591
