#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_HistoryArticle.cshtml")]
    public partial class HistoryArticle : System.Web.Mvc.WebViewPage<List<Cotide.Web.Controllers.Blog.ViewModel.HistoryArticleViewModel> >
    {
        public HistoryArticle()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Views\Blog\_HistoryArticle.cshtml"
WriteLiteral("<legend> <lable>  最近的文章</lable> </legend> ");

            
            #line default
            #line hidden
            
            #line 2 "..\..\Views\Blog\_HistoryArticle.cshtml"
                                           if (Model != null && Model.Count > 0)
   {
            
            #line default
            #line hidden
WriteLiteral("  <ul class=\"nav nav-pills nav-stacked\">\r\n");


            
            #line 4 "..\..\Views\Blog\_HistoryArticle.cshtml"
 foreach (var item in Model)
{
            
            #line default
            #line hidden
WriteLiteral("  <li>");


            
            #line 5 "..\..\Views\Blog\_HistoryArticle.cshtml"
  Write(Html.ActionLink(item.ArticleTitle, "Article", "Blog", new  {
                                                                             @id=item.ArticleId
                                                                           }, new
                                                                            {
                                                                                @title = item.FullArticleTitle,
                                                                               
                                                                            }));

            
            #line default
            #line hidden
WriteLiteral("  </li>   ");


            
            #line 11 "..\..\Views\Blog\_HistoryArticle.cshtml"
                                                                                        }
            
            #line default
            #line hidden
WriteLiteral(" </ul>  ");


            
            #line 11 "..\..\Views\Blog\_HistoryArticle.cshtml"
                                                                                                 }
   else
   { 

            
            #line default
            #line hidden
WriteLiteral("        <p style=\"text-align: center;\">\r\n            暂无文章\r\n        </p>\r\n");


            
            #line 17 "..\..\Views\Blog\_HistoryArticle.cshtml"
  }  

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
