#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Blog\_HomeArticleComment.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/_HomeArticleComment.cshtml")]
    public partial class HomeArticleComment : System.Web.Mvc.WebViewPage<List<HomeArticleCommentViewModel>>
    {
        public HomeArticleComment()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\_HomeArticleComment.cshtml"
  
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral(" ");


WriteLiteral(" ");


WriteLiteral(" <legend>\r\n    <lable>  最近评论</lable>\r\n</legend>\r\n");


            
            #line 9 "..\..\Views\Blog\_HomeArticleComment.cshtml"
  if (Model != null && Model.Count > 0)
 { 

            
            #line default
            #line hidden
WriteLiteral("<ul class=\"nav nav-pills nav-stacked\">     \r\n");


            
            #line 12 "..\..\Views\Blog\_HomeArticleComment.cshtml"
  foreach (var item in Model)
 {   

            
            #line default
            #line hidden
WriteLiteral("    <li>\r\n        <a href=\"");


            
            #line 15 "..\..\Views\Blog\_HomeArticleComment.cshtml"
            Write(Url.Action("Article", "Blog", new { @id = item.ArticleId }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 15 "..\..\Views\Blog\_HomeArticleComment.cshtml"
                                                                                 Write(item.FullContent);

            
            #line default
            #line hidden
WriteLiteral("\" >  ");


            
            #line 15 "..\..\Views\Blog\_HomeArticleComment.cshtml"
                                                                                                       Write(item.NickName);

            
            #line default
            #line hidden
WriteLiteral(":");


            
            #line 15 "..\..\Views\Blog\_HomeArticleComment.cshtml"
                                                                                                                      Write(item.Content);

            
            #line default
            #line hidden
WriteLiteral("  </a>\r\n    </li> \r\n");


            
            #line 17 "..\..\Views\Blog\_HomeArticleComment.cshtml"
 }       

            
            #line default
            #line hidden
WriteLiteral("</ul>\r\n");


            
            #line 19 "..\..\Views\Blog\_HomeArticleComment.cshtml"
 }
 else
 { 

            
            #line default
            #line hidden
WriteLiteral("    <p style=\"text-align: center;\">\r\n        暂无评论\r\n    </p>\r\n");


            
            #line 25 "..\..\Views\Blog\_HomeArticleComment.cshtml"
 }

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
