#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Cotide.Framework.Collections.PagedList<Cotide.Web.Controllers.Blog.ViewModel.ArticleViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\Index.cshtml"
  
    ViewBag.Title = @Html.Raw("李小潮'Blog  (＞﹏＜) ");
    ViewBag.Keywords = @Html.Raw("开发者,程序员,编程,代码,极客,Programmer,Coder,Code,Coding,个人博客,IT学习");
    ViewBag.Description = @Html.Raw("李小潮'Blog ");
    Layout = "~/Views/Shared/_BlogLayout.cshtml";


            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 7 "..\..\Views\Blog\Index.cshtml"
Write(Html.StyleSheet("pagerStyle.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


WriteLiteral("<ul class=\"breadcrumb\"> <li><a href=\"");


            
            #line 9 "..\..\Views\Blog\Index.cshtml"
                                Write(Url.Action("Index","Blog"));

            
            #line default
            #line hidden
WriteLiteral("\"  title=\"首页\">首页</a> <span class=\"divider\">/</span></li> <li  class=\"active\"> 日志文" +
"章  </li>  </ul>\r\n");


            
            #line 10 "..\..\Views\Blog\Index.cshtml"
 if (Model!=null && Model.Count > 0)
  {   
    foreach (var item in Model)
      {

            
            #line default
            #line hidden
WriteLiteral("    <section> <fieldset> <legend>\r\n           ");


            
            #line 15 "..\..\Views\Blog\Index.cshtml"
      Write(Html.ActionLink(item.ArticleTitle, "Article", "Blog", new {@id = item.ArticleId},
                                       new
                                           {
                                               @title = item.FullArticleTitle, 
                                               @class = "color_Black"
                                           }));

            
            #line default
            #line hidden
WriteLiteral("  </legend> <p> \r\n");


            
            #line 21 "..\..\Views\Blog\Index.cshtml"
                 if (item.ArticleTags != null && item.ArticleTags.Count>0)
             { 

            
            #line default
            #line hidden
WriteLiteral("                  ");

WriteLiteral("标签： \r\n");


            
            #line 24 "..\..\Views\Blog\Index.cshtml"
                    foreach (var articleTag in item.ArticleTags)
                   {

            
            #line default
            #line hidden
WriteLiteral("                       <a rel=\"tag\" href=\"");


            
            #line 26 "..\..\Views\Blog\Index.cshtml"
                                     Write(Url.Action("Tag", "Blog", new {@id = articleTag.Key}));

            
            #line default
            #line hidden
WriteLiteral("\"> ");


            
            #line 26 "..\..\Views\Blog\Index.cshtml"
                                                                                              Write(articleTag.Value);

            
            #line default
            #line hidden
WriteLiteral("</a>   \r\n");


            
            #line 27 "..\..\Views\Blog\Index.cshtml"
                   }
            
            #line default
            #line hidden
WriteLiteral(" <br/>   ");


            
            #line 27 "..\..\Views\Blog\Index.cshtml"
                             }

            
            #line default
            #line hidden

            
            #line 28 "..\..\Views\Blog\Index.cshtml"
Write(item.CreateTime.ToString("yyyy年MM月dd日 hh:mm:ss"));

            
            #line default
            #line hidden
WriteLiteral("  </p>  <p style=\"text-indent: 2em;\"> ");


            
            #line 28 "..\..\Views\Blog\Index.cshtml"
                                                                                  Write(Html.Raw(item.Content));

            
            #line default
            #line hidden
WriteLiteral("</p> </fieldset> \r\n<p class=\"posted\"><span class=\"comments\">   ");


            
            #line 29 "..\..\Views\Blog\Index.cshtml"
                                       Write(item.ReadCount);

            
            #line default
            #line hidden
WriteLiteral("  阅读 </span>    <span class=\"comments\">");


            
            #line 29 "..\..\Views\Blog\Index.cshtml"
                                                                                             Write(item.CommentCount);

            
            #line default
            #line hidden
WriteLiteral(" 评论 </span> <span class=\"readLink\">  ");


            
            #line 29 "..\..\Views\Blog\Index.cshtml"
                                                                                                                                                    Write(Html.ActionLink("阅读全文", "Article", "Blog", new { @id = item.ArticleId }, new { @title = "阅读全文" }));

            
            #line default
            #line hidden
WriteLiteral("</span> </p>\r\n    </section> ");


            
            #line 30 "..\..\Views\Blog\Index.cshtml"
               }   
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Blog\Index.cshtml"
              Write(Html.Pager("pageIndex", Model.PageSize, Model.TotalCount));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Blog\Index.cshtml"
                                                                               
  }
else
{ 

            
            #line default
            #line hidden
WriteLiteral("     <p> 暂无内容</p>\r\n");


            
            #line 35 "..\..\Views\Blog\Index.cshtml"
}
            
            #line default
            #line hidden
WriteLiteral(" ");


        }
    }
}
#pragma warning restore 1591
