#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Blog\Project.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/Project.cshtml")]
    public partial class Project : System.Web.Mvc.WebViewPage<ProjectViewModel>
    {
        public Project()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\Project.cshtml"
  
    ViewBag.Title = Html.Raw( Model.ProjectName +" - 代表作品 - 李小潮'Blog");
    ViewBag.Keywords = @Html.Raw("开发者,程序员,编程,代码,极客,Programmer,Coder,Code,Coding,个人博客,IT学习");
    ViewBag.Description = @Html.Raw("李小潮'Blog ");
    Layout = "~/Views/Shared/_BlogLayout.cshtml";


            
            #line default
            #line hidden


WriteLiteral("    <ul class=\"breadcrumb\">\r\n        <li><a href=\"");


            
            #line 10 "..\..\Views\Blog\Project.cshtml"
                Write(Url.Action("Index", "Blog", new { @domain =ViewData["domain"]}));

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n            title=\"首页\">首页</a> <span class=\"divider\">/</span></li>\r\n        <l" +
"i><a href=\"");


            
            #line 12 "..\..\Views\Blog\Project.cshtml"
                Write(Url.Content(string.Format("~/{0}/Blog/ZuoPin",ViewData["domain"])));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n            title=\"代表作品\">代表作品</a> <span class=\"divider\">/</span> </li>\r\n      " +
"  <li class=\"active\">\r\n            ");


            
            #line 15 "..\..\Views\Blog\Project.cshtml"
       Write(Model.ProjectName);

            
            #line default
            #line hidden
WriteLiteral(" \r\n        </li>\r\n    </ul>\r\n    <legend>\r\n        <h3>\r\n            ");


            
            #line 20 "..\..\Views\Blog\Project.cshtml"
       Write(Model.ProjectName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    </legend>\r\n    <p>\r\n         ");


            
            #line 23 "..\..\Views\Blog\Project.cshtml"
    Write(Html.Raw(@Model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n         </p>\r\n        ");


        }
    }
}
#pragma warning restore 1591
