#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17626
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cotide.Portal.Views.Blog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 7 "..\..\Views\Blog\ZuoPin.cshtml"
    using Cotide.Web.Controllers.Blog.ViewModel;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Blog/ZuoPin.cshtml")]
    public partial class ZuoPin : System.Web.Mvc.WebViewPage<ZupPinViewModel>
    {
        public ZuoPin()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Blog\ZuoPin.cshtml"
  
    ViewBag.Title = Html.Raw("代表作品 - 李小潮'Blog");
    ViewBag.Keywords = @Html.Raw("开发者,程序员,编程,代码,极客,Programmer,Coder,Code,Coding,个人博客,IT学习");
    ViewBag.Description = @Html.Raw("李小潮'Blog ");
    Layout = "~/Views/Shared/_BlogLayout.cshtml";


            
            #line default
            #line hidden


WriteLiteral("  <ul class=\"breadcrumb\">\r\n        <li><a href=\"");


            
            #line 10 "..\..\Views\Blog\ZuoPin.cshtml"
                Write(Url.Action("Index", "Blog", new { @domain =Model.Domain}));

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n            title=\"首页\">首页</a> <span class=\"divider\">/</span></li>\r\n        <l" +
"i  class=\"active\"> 代表作品  </li>\r\n        \r\n    </ul>\r\n    <ul class=\"nav nav-tabs" +
"\">\r\n        <li ");


            
            #line 16 "..\..\Views\Blog\ZuoPin.cshtml"
        Write(ViewData["index"] == null ? "class=active" : "");

            
            #line default
            #line hidden
WriteLiteral("  > \r\n           <a href=\"");


            
            #line 17 "..\..\Views\Blog\ZuoPin.cshtml"
               Write(Url.Content(string.Format("~/{0}/Blog/ZuoPin",Model.Domain)));

            
            #line default
            #line hidden
WriteLiteral(" \">\r\n          <span>\r\n             全部</span></a></li> \r\n");


            
            #line 20 "..\..\Views\Blog\ZuoPin.cshtml"
          foreach (var item in Model.ProjectTypes)
          { 

            
            #line default
            #line hidden
WriteLiteral("        <li ");


            
            #line 22 "..\..\Views\Blog\ZuoPin.cshtml"
        Write(ViewData["index"]!=null&&int.Parse(ViewData["index"].ToString())==item.Id?"class=active":"" );

            
            #line default
            #line hidden
WriteLiteral(">\r\n            <a href=\"");


            
            #line 23 "..\..\Views\Blog\ZuoPin.cshtml"
                Write(Url.Action("ZuoPin", "Blog", new { @id =item.Id}));

            
            #line default
            #line hidden
WriteLiteral("\"><span>\r\n                ");


            
            #line 24 "..\..\Views\Blog\ZuoPin.cshtml"
           Write(item.TypeName);

            
            #line default
            #line hidden
WriteLiteral(" </span></a></li>\r\n");


            
            #line 25 "..\..\Views\Blog\ZuoPin.cshtml"
        }  

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");


            
            #line 27 "..\..\Views\Blog\ZuoPin.cshtml"
      if (Model.Projects != null && Model.Projects.Count > 0)
       { 
        for (int i = 0; i < Model.Projects.Count; i++)
       { 

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"container-fluid\">\r\n");


            
            #line 32 "..\..\Views\Blog\ZuoPin.cshtml"
         if (i % 2 == 0||i==0)
          { 

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"row-fluid \">\r\n            <div class=\"span2\">\r\n              " +
"  <img class=\"img-polaroid\" src=\"");


            
            #line 36 "..\..\Views\Blog\ZuoPin.cshtml"
                                          Write(Model.Projects[i].ProjectImg);

            
            #line default
            #line hidden
WriteLiteral(" \" />\r\n            </div>\r\n            <div class=\"span10 \">\r\n                <le" +
"gend><a class=\"color_Black\" href=\"");


            
            #line 39 "..\..\Views\Blog\ZuoPin.cshtml"
                                                Write(Url.Action("Project","Blog",new {@id=Model.Projects[i].Id}));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                  title=\"  ");


            
            #line 40 "..\..\Views\Blog\ZuoPin.cshtml"
                      Write(Model.Projects[i].ProjectName);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 41 "..\..\Views\Blog\ZuoPin.cshtml"
               Write(Model.Projects[i].ProjectName);

            
            #line default
            #line hidden
WriteLiteral(" </a></legend>\r\n                <p>\r\n                    ");


            
            #line 43 "..\..\Views\Blog\ZuoPin.cshtml"
               Write(Model.Projects[i].Introduction);

            
            #line default
            #line hidden
WriteLiteral(" </p>\r\n            </div>\r\n        </div>\r\n");


            
            #line 46 "..\..\Views\Blog\ZuoPin.cshtml"
       }
          else
          { 

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"row-fluid \">\r\n            <div class=\"span10 \">\r\n            " +
"    <legend><a class=\"color_Black\" href=\"");


            
            #line 51 "..\..\Views\Blog\ZuoPin.cshtml"
                                                Write(Url.Action("Project","Blog",new {@id=Model.Projects[i].Id}));

            
            #line default
            #line hidden
WriteLiteral(" \"\r\n                     title=\" ");


            
            #line 52 "..\..\Views\Blog\ZuoPin.cshtml"
                        Write(Model.Projects[i].ProjectName);

            
            #line default
            #line hidden
WriteLiteral(" \">\r\n                     ");


            
            #line 53 "..\..\Views\Blog\ZuoPin.cshtml"
                Write(Model.Projects[i].ProjectName);

            
            #line default
            #line hidden
WriteLiteral("</a></legend>\r\n                <p>\r\n                    ");


            
            #line 55 "..\..\Views\Blog\ZuoPin.cshtml"
               Write(Model.Projects[i].Introduction);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n            <div class=\"span2\">\r\n                <img c" +
"lass=\"img-polaroid\" src=\"");


            
            #line 58 "..\..\Views\Blog\ZuoPin.cshtml"
                                          Write(Model.Projects[i].ProjectImg);

            
            #line default
            #line hidden
WriteLiteral(" \">\r\n            </div>\r\n        </div> \r\n");


            
            #line 61 "..\..\Views\Blog\ZuoPin.cshtml"
}  

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");



WriteLiteral("    <p></p>\r\n");


            
            #line 64 "..\..\Views\Blog\ZuoPin.cshtml"
    } 
     }
       else
       { 

            
            #line default
            #line hidden
WriteLiteral("    <p style=\"text-align: center;\">\r\n        暂无内容\r\n    </p>\r\n");


            
            #line 71 "..\..\Views\Blog\ZuoPin.cshtml"
    }  

            
            #line default
            #line hidden
WriteLiteral("    ");


        }
    }
}
#pragma warning restore 1591
